import { useState, useEffect } from 'react';
import { getISOWeek, getISOWeekYear } from 'date-fns';
import './WeeklyAnalysis.css';

function WeeklyAnalysis() {
  const [analysisData, setAnalysisData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [expandedHypothesis, setExpandedHypothesis] = useState(null);
  const [expandedUncertainty, setExpandedUncertainty] = useState(null);
  const [expandedSignal, setExpandedSignal] = useState(null);

  useEffect(() => {
    async function loadLatestAnalysis() {
      try {
        // Try to load the most recent analysis file
        // In production, you would dynamically fetch the list of files
        // For now, we'll try a few recent weeks
        const currentDate = new Date();
        const attempts = [];
        
        // Generate potential file names for the last 4 weeks
        for (let i = 0; i < 4; i++) {
          const date = new Date(currentDate);
          date.setDate(date.getDate() - (i * 7));
          const year = getISOWeekYear(date);
          const weekNumber = getISOWeek(date);
          
          const weekStr = `${year}-${String(weekNumber).padStart(2, '0')}`;
          attempts.push(`/data/analysis/week_${weekStr}.json`);
        }

        // Try each file in order (silently)
        let data = null;
        for (const url of attempts) {
          try {
            const response = await fetch(url);
            if (response.ok) {
              data = await response.json();
              break;
            }
            // Silently continue on 404 - this is expected before first run
          } catch {
            // Silently continue to next attempt - network errors are also expected
          }
        }

        if (!data) {
          setError('No analysis data available yet. Check back after the weekly analysis runs.');
          setLoading(false);
          return;
        }

        setAnalysisData(data);
        setLoading(false);
      } catch (err) {
        // Only log unexpected errors (not 404s)
        if (err.message && !err.message.includes('404')) {
          console.error('Error loading analysis:', err);
        }
        setError('Failed to load analysis data');
        setLoading(false);
      }
    }

    loadLatestAnalysis();
  }, []);

  const toggleHypothesis = (index) => {
    setExpandedHypothesis(expandedHypothesis === index ? null : index);
  };

  const toggleUncertainty = (index) => {
    setExpandedUncertainty(expandedUncertainty === index ? null : index);
  };

  const toggleSignal = (index) => {
    setExpandedSignal(expandedSignal === index ? null : index);
  };

  if (loading) {
    return (
      <div className="weekly-analysis">
        <div className="loading">Loading AI analysis...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="weekly-analysis">
        <div className="error-message">{error}</div>
      </div>
    );
  }

  if (!analysisData || !analysisData.analysis) {
    return null;
  }

  const { analysis } = analysisData;

  return (
    <div className="weekly-analysis">
      {/* Disclaimer Banner - Always Visible */}
      <div className="disclaimer-banner">
        <div className="disclaimer-icon">⚠️</div>
        <div className="disclaimer-text">
          <strong>{analysis.disclaimer}</strong>
          <p>This analysis is generated by AI from aggregated data patterns and should be validated with additional sources.</p>
        </div>
      </div>

      {/* Analysis Header */}
      <div className="analysis-header">
        <h2>🤖 Weekly Intelligence Analysis</h2>
        <div className="analysis-metadata">
          <span className="metadata-item">
            📅 Week: {analysis.week_start} to {analysis.week_end}
          </span>
          <span className="metadata-item">
            🕐 Generated: {new Date(analysisData.generated_at).toLocaleString()}
          </span>
          <span className="metadata-item">
            🤖 Model: {analysisData.model}
          </span>
          <span className="metadata-item">
            📊 Version: {analysisData.prompt_version}
          </span>
        </div>
      </div>

      {/* Hypotheses Section */}
      <div className="analysis-section">
        <h3>💡 Intelligence Hypotheses</h3>
        <p className="section-description">
          Proposed patterns identified from this week's aggregate data. Each hypothesis includes supporting evidence, counter-evidence, and validation steps.
        </p>
        
        <div className="cards-container">
          {analysis.hypotheses.map((hypothesis, index) => (
            <div 
              key={index} 
              className={`analysis-card hypothesis-card ${expandedHypothesis === index ? 'expanded' : ''}`}
            >
              <div className="card-header" onClick={() => toggleHypothesis(index)}>
                <div className="card-title">
                  <span className="card-number">{index + 1}</span>
                  <span className="claim">{hypothesis.claim}</span>
                </div>
                <div className="card-badges">
                  <span className={`confidence-badge confidence-${hypothesis.confidence}`}>
                    {hypothesis.confidence}
                  </span>
                  <span className="expand-icon">
                    {expandedHypothesis === index ? '▼' : '▶'}
                  </span>
                </div>
              </div>
              
              {expandedHypothesis === index && (
                <div className="card-content">
                  <div className="content-section">
                    <h4>🎯 Why Now</h4>
                    <p>{hypothesis.why_now}</p>
                  </div>
                  
                  <div className="content-section">
                    <h4>✅ Supporting Signals</h4>
                    <ul>
                      {hypothesis.supporting_signals.map((signal, i) => (
                        <li key={i}>{signal}</li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="content-section">
                    <h4>⚠️ Counter Signals</h4>
                    <ul>
                      {hypothesis.counter_signals.map((signal, i) => (
                        <li key={i}>{signal}</li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="content-section">
                    <h4>🔍 Validation Steps</h4>
                    <ol>
                      {hypothesis.validation_steps.map((step, i) => (
                        <li key={i}>{step}</li>
                      ))}
                    </ol>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Uncertainties Section */}
      <div className="analysis-section">
        <h3>❓ Key Uncertainties</h3>
        <p className="section-description">
          Known gaps in available data that limit analysis confidence. Understanding what we don't know is crucial for intelligence assessment.
        </p>
        
        <div className="cards-container">
          {analysis.uncertainties.map((uncertainty, index) => (
            <div 
              key={index} 
              className={`analysis-card uncertainty-card ${expandedUncertainty === index ? 'expanded' : ''}`}
            >
              <div className="card-header" onClick={() => toggleUncertainty(index)}>
                <div className="card-title">
                  <span className="card-number">{index + 1}</span>
                  <span className="claim">{uncertainty.unknown}</span>
                </div>
                <span className="expand-icon">
                  {expandedUncertainty === index ? '▼' : '▶'}
                </span>
              </div>
              
              {expandedUncertainty === index && (
                <div className="card-content">
                  <div className="content-section">
                    <h4>💼 Why It Matters</h4>
                    <p>{uncertainty.why_it_matters}</p>
                  </div>
                  
                  <div className="content-section">
                    <h4>📊 Data Needed</h4>
                    <p>{uncertainty.what_data_would_reduce_uncertainty}</p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Watch Signals Section */}
      <div className="analysis-section">
        <h3>🔔 Signals to Watch</h3>
        <p className="section-description">
          Metrics to monitor with specific thresholds. If these thresholds are crossed, the recommended actions should be considered.
        </p>
        
        <div className="cards-container">
          {analysis.signals_to_watch.map((signal, index) => (
            <div 
              key={index} 
              className={`analysis-card signal-card ${expandedSignal === index ? 'expanded' : ''}`}
            >
              <div className="card-header" onClick={() => toggleSignal(index)}>
                <div className="card-title">
                  <span className="card-number">{index + 1}</span>
                  <span className="claim">{signal.signal}</span>
                </div>
                <span className="expand-icon">
                  {expandedSignal === index ? '▼' : '▶'}
                </span>
              </div>
              
              {expandedSignal === index && (
                <div className="card-content">
                  <div className="content-section threshold-section">
                    <h4>📏 Threshold</h4>
                    <div className="threshold-value">{signal.threshold}</div>
                  </div>
                  
                  <div className="content-section">
                    <h4>💼 Why It Matters</h4>
                    <p>{signal.why_it_matters}</p>
                  </div>
                  
                  <div className="content-section">
                    <h4>🎯 Recommended Action</h4>
                    <p>{signal.recommended_action}</p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Inputs Used */}
      <div className="analysis-footer">
        <h4>📋 Data Sources Used in This Analysis</h4>
        <div className="inputs-used">
          {analysis.inputs_used.map((input, index) => (
            <span key={index} className="input-tag">{input}</span>
          ))}
        </div>
      </div>
    </div>
  );
}

export default WeeklyAnalysis;
